@startuml
title -Ulma Game-
package System{
    class IWindow{
        
    }

    class WindowOpenGL{

    }
    IWindow <|.. WindowOpenGL

    class IApplicationCore{

    }

    class ApplicationCoreOpenGL{

    }
    IApplicationCore <|.. ApplicationCoreOpenGL
    WindowOpenGL <.. ApplicationCoreOpenGL


}
@enduml